### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by qodesmith** [nomocas/mini-wysiwyg#1]
I assume more documentation is in the works since this looks like a recent project. I'm eager to learn more!

At the moment, you're `usage` section shows appending `MiniWysiwyg.menu().el)` to the body (or somewhere). I've done that, but it disappears each time I edit conteditable  node that I've selected. Any thoughts? Hot keys work for bold & italics, although I notice they're being achieved with `<b>` and `<i>` tags. Would prefer span's with either pre-defined classes or inline styles.

Also, I take it font-awesome is a dependency for the meny? When it first shows up I see a few checkboxes, but that's it. I'll go download fa and see if that makes a difference. I look fwd to seeing more from this project!

**Comment by qodesmith** [comment]
Installed fa & the menu icons now show. I also compiled that `scss` file you guys have in the folder to css and it styles correctly. The menu is still `display-none` both in the css and inline-styled when I blur from the editable node.

**Comment by qodesmith** [comment]
Looks like the issue with the menu not displaying had to do with me using a `textarea` as opposed to a regular `div`. It works as expected now, showing & hiding as needed.

**Comment by marsPure** [comment]
+1

**Comment by nomocas** [comment]
Hello Guys,

I've added few docs and a workable example. 

I've also added a "replacer" functionality for nodes casting (b or i or ...  to span.your-class by example). 

Enjoy... ;)
